### ISSUE TITLE
How to define schema in Redshift

### ISSUE THREAD

**Issue by bbnsumanth** [databricks/spark-redshift#125]
I do not want to store my data in default PUBLIC schema,instead i want to store my tables to a custom schema.Any help on achieving this with spark redshift connector will very useful.

**Comment by JoshRosen** [comment]
Hi @bbnsumanth,

You should be able to pass schema-qualified table names in order to read or write tables from other schemas. For instance, you should be able to pass `my_schema.my_table_name` as the value of the  `dbtable` parameter. The `spark-redshift` library also knows how to respect quoting rules, so it should be capable of handling quoted schema or table names (in case you happen to want a table name which contains a dot), e.g. `dbtable="\"foo.bar\".baz"`.

If you're interested in learning how schema-qualified table names are handled internally, take a look at #102, which fixed some bugs related to this (for this reason, make sure that you're using the latest version of `spark-redshift` (0.5.2)).

Hope this helps!

**Comment by bbnsumanth** [comment]
Thank you,it is very helpful.
