### ISSUE TITLE
Unresolved dependency com.databricks#spark-redshift_2.10_2.11;0.5.2: not found

### ISSUE THREAD

**Issue by mukundrv** [databricks/spark-redshift#139]
If I add the  dependency 
libraryDependencies += "com.databricks" %% "spark-redshift_2.10" % "0.5.2"
when I build using sbt, I get the following error 
error] (*:update) sbt.ResolveException: unresolved dependency: com.databricks#spark-redshift_2.10_2.11;0.5.2: not found

where as, if I add 
libraryDependencies += "com.databricks" %% "spark-redshift" % "0.5.2"
it builds successfuly. 

The documentation at http://spark-packages.org/package/databricks/spark-redshift says to use the former

**Comment by JoshRosen** [comment]
Hi @mukundrv,

This is expected behavior; the correct instructions should read

```
libraryDependencies += "com.databricks" %% "spark-redshift" % "0.5.2"
```

This is a problem with the auto-generated documentation on spark-packages.org, so I'm going to ping @mengxr and @brkyvz to fix it.

In the meantime, I'm going to close this issue as I don't think there's any more action to take from the `spark-redshift` POV. Thanks!
