### ISSUE TITLE
com.amazonaws.services.s3.model.AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header

### ISSUE THREAD

**Issue by jelez** [databricks/spark-redshift#144]
This particular piece of code used to work but after aws sdk has been updated writing to S3 is broken. I would appreciate any assistance:
```
16/01/03 23:24:08 INFO Test$: Writing to Redshift: staging.messages_20160103_232152
16/01/03 23:24:09 WARN Utils$: An error occurred while trying to read the S3 bucket lifecycle configuration
com.amazonaws.services.s3.model.AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 9DBF5750XXXXX29A), S3 Extended Request ID: gaPPrdaUYPrRXXXXXrTWw2IZQk44bmeoa/gQDJT8CaQfFdmXXXXXEaG5dAYu9/UOv/7t6XXXXXE=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1077)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3714)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3664)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketLifecycleConfiguration(AmazonS3Client.java:1939)
	at com.databricks.spark.redshift.Utils$.checkThatBucketHasObjectLifecycleConfiguration(Utils.scala:92)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:368)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:170)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:146)
```
Compile info from my pom.xml:
```
<scala.tools.version>2.10</scala.tools.version>
<scala.version>2.10.4</scala.version>
<spark.version>1.5.2</spark.version>
<spark-avro.version>2.0.1</spark-avro.version>
...
<dependency>
	<groupId>com.databricks</groupId>
	<artifactId>spark-avro_${scala.tools.version}</artifactId>
	<version>${spark-avro.version}</version>
	<scope>provided</scope>
</dependency>
<dependency>
	<groupId>com.amazon</groupId>
	<artifactId>redshift-driver</artifactId>
	<version>1.1.7</version>
</dependency>
<dependency>
	<groupId>com.databricks</groupId>
	<artifactId>spark-redshift_${scala.tools.version}</artifactId>
	<version>0.5.2</version>
</dependency>
```
com.amazonaws.aws-java-sdk resolved dependency version 1.9.16

Note: I can write to the same bucket Parquet files from the same application.

Also which version of aws sdk is recommended?

**Comment by jelez** [comment]
Also which version of aws sdk is recommended?

**Comment by JoshRosen** [comment]
Thanks for including all of the information RE: dependencies. Just one minor clarification, though: the scary-looking error message that you posted was actually a _warning_ indicating that an optional operation, designed to print helpful configuration suggestions, failed, but this isn't actually the exception which caused your write to fail. If a second exception occurs later in the same log, could you post that stacktrace as well so that I can get a more complete picture of what might be failing?

**Comment by JoshRosen** [comment]
Also, which version of the AWS SDK were you using before, prior to upgrading to 1.9.16?

**Comment by JoshRosen** [comment]
A quick trip to Google/StackOverflow suggests that this particular "AWS authentication requires a valid Date or x-amz-date header" error might be caused by an incompatibility between certain JodaTime versions and certain newer Java 8 JDKs: https://stackoverflow.com/questions/32058431/aws-java-sdk-aws-authentication-requires-a-valid-date-or-x-amz-date-header

Could you check whether the diagnostic steps + workarounds linked from that thread solve your problem?

**Comment by jelez** [comment]
hey Josh,
I do not remember which version of AWS SDK I tested before when it worked.
However, using joda-time 2.9 did the trick. Now it works. Thanks alot!
```
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>2.9</version>
		</dependency>
```
Probably the handling should not be a WARN but an ERROR because the import actually failed. if you see in the error I got Access Denied so it could not write to S3 for the COPY command.

**Comment by JoshRosen** [comment]
@jelez, to clarify slightly I am saying that your import failure was probably caused by another exception which appears further down in the log. This particular line needs to be a WARN because it's actually plausible that the bucket lifecycle check can fail due to permission issues while the write succeeds because those are controlled by separate IAM permissions.

**Comment by jelez** [comment]
@JoshRosen I have run it multiple times and I did not see any other exception. without the joda-time dependency I get this error. With it the error disappears.
Thank you.

**Comment by JoshRosen** [comment]
@jelez, to illustrate why I don't think that this warning message is causing your write to fail, take a look at the `spark-redshift` 0.5.2 code (since that's the version that you mentioned that you're using):

The part of the write path which triggers this message message is RedshiftWriter.scala#L368](https://github.com/databricks/spark-redshift/blob/v0.5.2/src/main/scala/com/databricks/spark/redshift/RedshiftWriter.scala#L368). Inside of `Utils.checkThatBucketHasObjectLifecycleConfiguration`, only non-fatal exceptions are logged and they are not re-thrown: see [Utils.scala#L108](https://github.com/databricks/spark-redshift/blob/v0.5.2/src/main/scala/com/databricks/spark/redshift/Utils.scala#L108).

Now I imagine that you might see a _similar_ stacktrace with a "AWS authentication requires a valid Date or x-amz-date header" which is thrown by code later in the write path, which _would_ cause the job to fail. Can you share the portion of the log immediately following the error message that you posted in this issue?
