### ISSUE TITLE
Push more date string comparisons to Redshift

### ISSUE THREAD

**Issue by JoshRosen** [databricks/spark-redshift#155]
Originally reported by @gregrahn in #152:

> 
> Interestingly enough using
> ```
> t.filter($"c_date"     >= "2016-01-01")
> ```
> does not push any SQL filter through to the UNLOAD command which, while returns the correct result, scans much more data on the Redshift side than need be and should also be fixed.

**Comment by marmbrus** [comment]
This is likely because we cast this expression weirdly to be compatible with Hive.  Specifically I think this turns into, `CAST(c_date AS STRING) >= "2016-01-01"`, and we don't push down casts down into data sources.

The reason for casting this way is because users currently expect the following to work `c_date >= "2016"`.

**Comment by JoshRosen** [comment]
It sounds like pushdown in this case would require changes to Spark itself, so I'm going to resolve this issue as "wontfix" for `spark-redshift` itself since I think it's out-of-scope for this library.
