### ISSUE TITLE
spark redshift takes hell lot of time to save 

### ISSUE THREAD

**Issue by ibnipun10** [databricks/spark-redshift#183]
Hi,

I have a dataframe with 1 record. It takes around 4 min to write to redshift from spark using df.save()
Here is the code 

groupDf.write.format("com.databricks.spark.redshift").option("url", REDSHIFT_URL).option("dbtable", REDSHIFT_PAGEVIEW_TBL).option('tempdir', S3_URL).mode('Append').save()

I have 1 master and 2 executors with 2 cores each in executors. All the machines are in AWS.

**Comment by JoshRosen** [comment]
Which versions of Spark and `spark-redshift` are you using?

It would be good to figure out whether the slowness is in Spark itself or whether Redshift is being slow during the `COPY`.

**Comment by ibnipun10** [comment]
Please close this one. Spark created 200 partitions by default. I have only 2 executors. I needed to coalase the dataframe to decrease the number of partitions. Once I did that to 4 partitions I saw an imporvement from 4 min to 14 sec, thats huge.  I can provide one suggestion. If the api for save can accepts one more parameter to accept number of partition (default can be none) and repartition the dataframe internally, that would be great.

**Comment by JoshRosen** [comment]
You can coalesce yourself prior to the write, so I don't necessarily see why we need to add an API for this to `spark-redshift`.

**Comment by ibnipun10** [comment]
Adding additional parameter may help those who may see this issue and provide them a clue as to where can be the problem is

**Comment by JoshRosen** [comment]
I think the right solution here is adding a tip in the documentation rather than an unnecessary configuration parameter / feature.

**Comment by ibnipun10** [comment]
Yep, somewhere if we can mention,in the performance section that more the partitions more time it can take to write to redshift, could be a boon for people like me

**Comment by dmadzharov** [comment]
Hi all,
i have a similar problem. I am trying to save a dataframe which has 6 records but it takes more than 15 mins to save it to the redshift. I also tried to coalesce to 4 partitions (default it was 200) but it the result is the same...Actually if i keep waiting at some point of the time it is failing with the following error:
`org.apache.spark.SparkException: Job aborted due to stage failure: ResultStage 22 (save at <console>:50) has failed the maximum allowable number of times: 4. Most recent failure reason: org.apache.spark.shuffle.MetadataFetchFailedException: Missing an output location for shuffle 25 .....`

 Any idea how can i optimize this ? This is the code i use: 

`def saveRSTable(df: org.apache.spark.sql.DataFrame, tableName: String) : Unit = {
  val rDF = df.coalesce(4)
   rDF.write
  .format("jdbc")
  .option("driver", redshiftdriver)
  .option("dbtable", tableName)
  .option("url", redshifturl)
  .mode(SaveMode.Append)
  .save()`

**Comment by yihuazh** [comment]
is higher version Spark data frame write method has better performance?  , in our app, it save very slow ,even  500 records  ii needs to cost 6 minutes ...  I try different partitions , doesn't help

**Comment by kyprifog** [comment]
I confirm the same behavior, I had a dataframe with only 2 records and it took several minutes to save to redshift.  There is something clearly wrong.  Watch the trace it seems like it makes a call to S3 (probbably for tmp operations) at least once for every record, if not multiple times?  I think this may be whats slowing it down.

**Comment by argenisleon** [comment]
Same problem here.
It takes 10 min to save 10000 records.
I try to repartition the dataframe without any improvement

**Comment by PoojithaSornapudi** [comment]
Even me, it is taking 10 min to save 10000 records to redshift. even though i used coalesce
