### ISSUE TITLE
How to specify parallel thread for redshift.

### ISSUE THREAD

**Issue by manisha803** [databricks/spark-redshift#236]
I am loading data into Redshift EMR. It is running damm slow. How to load table in redshift with Parallel thread.

**Comment by JoshRosen** [comment]
The load is already parallel. Redshift's Avro loader, which this library uses, isn't super performant; see #73 for a discussion of using CSV in order to speed things up.

**Comment by joeharris76** [comment]
@manisha803 I was having trouble with something similar. Turns out I needed to parallelise my collection of things to be loaded _before_ calling the write to Redshift. 

```
    // OLD >> loadList.collect.foreach { loadThis =>
    // Revision to run the extracts in parallel
    val loadPar = loadList.collect.par 
    loadPar.foreach { loadThis =>
      try{
```
That `.par` creates a parallelised collection and Spark performs the `.foreach` in parallel for all members of the collection (to the extent that it can given available cluster resources). HTH
