### ISSUE TITLE
Incorrect decimal conversion loading table to DF

### ISSUE THREAD

**Issue by beeva-arturomartinez** [databricks/spark-redshift#243]
I am having some troubles with decimal conversion when I load DF from table sales in this tutorial:

https://github.com/databricks/spark-redshift/tree/branch-1.x/tutorial

After load DataFrame with table data if I filter by salesid 102373 and make show 
`val salesQuery = """SELECT salesid, listid, sellerid, buyerid,
                               eventid, dateid, qtysold, pricepaid, commission
                        FROM hbgdwc.temp_sales
                        ORDER BY saletime DESC LIMIT 10000"""
    val salesDF = sqlContext.read
      .format("com.databricks.spark.redshift")
      .option("url", jdbcURL)
      .option("tempdir", tempS3Dir)
      .option("query", salesQuery)
      .load()
    salesDF.filter(salesDF("salesid") === 102373).show(1)`

I recive the result below:

```
+-------+------+--------+-------+-------+------+-------+---------+----------+
|salesid|listid|sellerid|buyerid|eventid|dateid|qtysold|pricepaid|commission|
+-------+------+--------+-------+-------+------+-------+---------+----------+
| 102373|117133|   26190|  35491|   2141|  2191|      4|100800.00|  15120.00|
+-------+------+--------+-------+-------+------+-------+---------+----------+
```

But in the example and in Redshift Table commision field has a value of  151.20. I think that there is a bug with dot decimal conversion.

**Comment by JoshRosen** [comment]
Looks like this may be a bug. Which versions of `spark-redshift` and Spark are you using?

**Comment by beeva-arturomartinez** [comment]
I use Spark 1.6.1 and spark-redshift 1.0.0 for Scala 2.10. My Redshift cluster version is 1.0.1070

Thx.

**Comment by beeva-ignaciogonzalez** [comment]
I've made probes and changing linux locale from es_ES.UTF-8 to en_US.UTF-8 the problem doesn't appear so it could be decimal separator character configuration. Is this separator configurable and not env dependent?

**Comment by JoshRosen** [comment]
@beeva-ignaciogonzalez, that's a great find: it looks like `new DecimalFormat()` is locale-sensitive and we call that method directly rather than explicitly freezing the locale: https://github.com/databricks/spark-redshift/blob/7ae3b9a53440693c5af9c84ae7f02f077e65e354/src/main/scala/com/databricks/spark/redshift/Conversions.scala#L48

It looks like Spark itself had a similar problem and worked around it by hardcoding a US locale: https://issues.apache.org/jira/browse/SPARK-13515

This should hopefully be easy to fix by applying the same change here.

**Comment by JoshRosen** [comment]
I've opened #249 to fix this.
