### ISSUE TITLE
CREATE statement

### ISSUE THREAD

**Issue by chanansh** [databricks/spark-redshift#255]
How can one CREATE a table programically from within pySpark?

> Py4JJavaError: An error occurred while calling o108.load.
> : java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near "create";
> 	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(ErrorResponse.java:1830)
> 	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(PGMessagingContext.java:822)
> 	at com.amazon.redshift.client.PGMessagingContext.handleMessage(PGMessagingContext.java:647)
> 	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(InboundMessagesPipeline.java:312)
> 	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(PGMessagingContext.java:1080)
> 	at com.amazon.redshift.client.PGMessagingContext.getParameterDescription(PGMessagingContext.java:996)
> 	at com.amazon.redshift.client.PGClient.prepareStatement(PGClient.java:1857)
> 	at com.amazon.redshift.dataengine.PGBatchQueryExecutor.<init>(PGBatchQueryExecutor.java:135)
> 	at com.amazon.redshift.dataengine.PGDataEngine.prepare(PGDataEngine.java:228)
> 	at com.amazon.jdbc.common.SPreparedStatement.<init>(Unknown Source)
> 	at com.amazon.jdbc.jdbc4.S4PreparedStatement.<init>(Unknown Source)
> 	at com.amazon.redshift.core.jdbc4.PGJDBC4PreparedStatement.<init>(PGJDBC4PreparedStatement.java:49)
> 	at com.amazon.redshift.core.jdbc4.PGJDBC4ObjectFactory.createPreparedStatement(PGJDBC4ObjectFactory.java:119)
> 	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
> 	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
> 	at com.databricks.spark.redshift.JDBCWrapper.resolveTable(RedshiftJDBCWrapper.scala:168)
> 	at com.databricks.spark.redshift.RedshiftRelation$$anonfun$schema$1.apply(RedshiftRelation.scala:65)
> 	at com.databricks.spark.redshift.RedshiftRelation$$anonfun$schema$1.apply(RedshiftRelation.scala:60)
> 	at scala.Option.getOrElse(Option.scala:120)
> 	at com.databricks.spark.redshift.RedshiftRelation.schema$lzycompute(RedshiftRelation.scala:60)
> 	at com.databricks.spark.redshift.RedshiftRelation.schema(RedshiftRelation.scala:59)
> 	at org.apache.spark.sql.execution.datasources.LogicalRelation.<init>(LogicalRelation.scala:37)
> 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:606)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
> 	at py4j.Gateway.invoke(Gateway.java:259)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:209)
> Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: syntax error at or near "create";
> 	... 33 more
>

**Comment by JoshRosen** [comment]
This is supposed to work, so I'm going to need more information in order to help you debug this. First, which versions of Spark and `spark-redshift` are you using?

If you look at the Spark driver logs, you should see an `INFO`-level [log message](https://github.com/databricks/spark-redshift/blame/95d92cdd730374939deb4488f1d8427fd41f29aa/src/main/scala/com/databricks/spark/redshift/RedshiftWriter.scala#L124) from the `RedshiftWriter` class which logs the complete `CREATE TABLE` statement that is issued against Redshift. Could you share that log output to see if we can spot what might be causing the syntax error?

Also, just to narrow down possibilities, does your table name contain any special characters or spaces? I believe that this is supposed to work because we quote / escape, but it's possible that there's a bug.
