### ISSUE TITLE
How to output RDD[GenericRecord] to redshift w/o introducing case class?

### ISSUE THREAD

**Issue by tzhang101** [databricks/spark-redshift#267]
HI, We have RDD[GenericRecord], 
is spark-redshift support output RDD[GenericRecord] to redshift 
directly WITHOUT mapping each GenericRecord to a case class object first?

**Comment by JoshRosen** [comment]
What's `GenericRecord` in this case? An Avro record?

**Comment by tzhang101** [comment]
yes, it is avro GenericRecord.

**Comment by JoshRosen** [comment]
If you're starting with a bunch of Avro files in S3 and want to append to an existing Redshift table then it may be easiest to just directly issue a `COPY` statement and skip the use of Spark as an intermediary.

Otherwise, I think that you're going to want to first convert your `RDD[GenericRecord]` into a Spark `DataFrame` / `Dataset` so that this library can be used. I don't think that [`spark-avro`](https://github.com/databricks/spark-avro) necessarily exposes the schema inference / conversion functions, but you might be able to copy and re-use some of the internal functions from that library.
