### ISSUE TITLE
Example of using HadoopInputFormat

### ISSUE THREAD

**Issue by AlexMikhalev** [databricks/spark-redshift#272]
I already have a tables from Redshit unloaded with UNLOAD command and I would like to use 

```
import com.databricks.spark.redshift.RedshiftInputFormat

val records = sc.newAPIHadoopFile(
  path,
  classOf[RedshiftInputFormat],
  classOf[java.lang.Long],
  classOf[Array[String]])
```

Fully documented example will help.

**Comment by JoshRosen** [comment]
Yeah, the existing README documentation isn't super useful. Take a look at the source code to see how `RedshiftInputFormat` is used in the existing code: I'm not sure how easy this will be to use because `RedshiftInputFormat` itself doesn't handle any type conversion, etc.

If you're trying to read already-unloaded files for which you know the table schema then take a look at the `redshiftFile` method: https://github.com/databricks/spark-redshift/blob/d50ab752b5341955bb09adebd9fff79a197367c5/src/main/scala/com/databricks/spark/redshift/package.scala#L49

**Comment by JoshRosen** [comment]
Marking this as "won't fix" for now to declutter the issue backlog. If someone wants to write documentation then please submit a PR.
