### ISSUE TITLE
Backport #277 to branch-1.x

### ISSUE THREAD

**Issue by apurva-sharma** [databricks/spark-redshift#304]
I ran into the same issue as https://github.com/databricks/spark-redshift/issues/274
In spite of setting aws_iam_role, my job fails
"AWS Access Key ID and Secret Access Key must be specified"
Could I please request a backport of this to the 1.x branch?

**Comment by JoshRosen** [comment]
I don't want to backport #274 without also backporting the other improvements in #291 which guard against misconfiguration when using IAM. Given that #291 introduces a compatibility-breaking change, we'd have to bump to a new major version number which would be confusing because we're already using 2.x and 3.x for versions that are compatible with Spark 2.0.

Thus, I'm going to have to mark this as "won't fix" but you're welcome to patch this yourself in a custom fork / build.

**Comment by apurva-sharma** [comment]
Thanks for the comments Josh, I applied your patch and it works fine.
Will upgrade to use the latest version once the spark cluster moves to 2.X
