### ISSUE TITLE
Saving to Redshift error

### ISSUE THREAD

**Issue by owb964** [databricks/spark-redshift#314]
The code below is meant to 1) load an existing table from Redshift called test123 into my S3 directory, 2) register it as a temporary table, and then 3) save it back to Redshift to a new table called test456:

```
val salesDF = hiveContext.read
    .format("com.databricks.spark.redshift")
    .option("url", jdbcUrl)
    .option("tempdir", tempS3Dir)
    .option("dbtable", "public.test123")
    .load()

salesDF.registerTempTable("myevent")

hiveContext.sql("SELECT * FROM myevent")
    .write.format("com.databricks.spark.redshift")
    .option("url", jdbcUrl)
    .option("tempdir", tempS3Dir)
    .option("dbtable", "public.test456")
    .mode(SaveMode.Overwrite)
    .save()
```

Note that I've already defined jdbcUrl and tempS3Dir.

The first two parts (the `load` and `registerTempTable`) seem to be working fine. I've gone into the specified S3 directory to verify that the contents of the test123 table were loaded. However, there's an error with the last part, saving to Redshift. This is the error that was thrown:

> java.lang.IncompatibleClassChangeError: class com.databricks.spark.avro.AvroRelation has interface org.apache.spark.sql.sources.TableScan as super class

From previous posts, this error seems to suggests that I'm using the incorrect version of spark-avro. However, I'm using Scala 2.11, Spark 1.6.1, and the spark-avro_2.11-2.0.0.jar, which should be correct. (I've also tried spark-avro_2.11-2.0.1.jar and spark-avro_2.10-2.0.0.jar in case.) Any suggestions or ideas?

**Comment by JoshRosen** [comment]
Which version of `spark-redshift` are you using?

**Comment by owb964** [comment]
I'm using the spark-redshift_2.11-1.1.0.jar

**Comment by JoshRosen** [comment]
I've seen this issue in the past and have generally been unable to reproduce it. We test against Spark 1.6.0 and Spark Avro 2.0.1 as part of our test matrix in https://github.com/databricks/spark-redshift/blob/v1.1.0/.travis.yml#L28, so this case should, in theory, be covered. Maybe there's a problem specific to 1.6.1? Given how we've generally had a good track record of binary compatibility in Spark, this problem is more likely a classpath misconfiguration issue specific to your environment.

In the absence of very specific detail on your effective driver classpath I'm afraid that I'm probably not going to be able to provide much more help here.
