### ISSUE TITLE
Redshift sqlContext.read fails with S3 input path does not exist - but it does

### ISSUE THREAD

**Issue by gregrahn** [databricks/spark-redshift#38]
I'm not sure if this is spark-redshift specific, but wondered if you have encountered this issue when using `sqlContext.read` from a Redshift table.

```
15/08/06 10:19:16 INFO SparkContext: Created broadcast 0 from newAPIHadoopFile at RedshiftRelation.scala:82
org.apache.hadoop.mapreduce.lib.input.InvalidInputException: Input path does not exist: s3://spark-temp-dir/19380690-5730-451a-b741-8245b27da674
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.listStatus(FileInputFormat.java:285)
  at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:340)
  at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:95)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
  at scala.Option.getOrElse(Option.scala:120)
...
```
However Spark has successfully unloaded the table to S3 as show by:
```
Gregs-MacBook-Pro:spark-scripts grahn$ aws s3 ls s3://spark-temp-dir/19380690-5730-451a-b741-8245b27da674/
2015-08-06 10:19:15        335 0000_part_00
2015-08-06 10:19:15        338 0001_part_00
```
Complete scripts of Spark setup, etc. in this gist:
https://gist.github.com/gregrahn/b63fea668d27d6265434

**Comment by marmbrus** [comment]
Hmmm, could it just be S3 eventual consistency?  I do often see files missing briefly due to this.

**Comment by yhuai** [comment]
For your temp dir, can you use `s3n` as the scheme (`"tempdir", "s3n://spark-temp-dir"`)?

**Comment by gregrahn** [comment]
@marmbrus For reference [S3 FAQ](https://aws.amazon.com/s3/faqs/) says
> Amazon S3 buckets in all Regions provide read-after-write consistency for PUTS of new objects...
Which should be the case here.

@yhuai The `s3n` did work for me, and just to add, only using `s3` fails every time.  Maybe the README should be updated to reflect that.

**Comment by jaley** [comment]
@gregrahn I get that all the time. Are you running locally and just adding `hadoop-aws` to your classpath as a dependency? You'll probably find that the same code (with `s3://`) works fine on EMR. I think you have to actually register `s3://` in `hdfs-site.xml` or something like that for it to work - not sure exactly, but it's definitely a local setup issue. Not a `spark-redshift` issue, just a general S3 configuration drama.

**Comment by JoshRosen** [comment]
I also ran into some issues with `s3://` so I'm wondering whether it would make sense to log a warning if we see that scheme being used.

**Comment by yhuai** [comment]
Have a clarification question. Does the scheme `s3` mean the original S3 block fileystem? If so, I think it cannot read normal S3 data, right?

**Comment by JoshRosen** [comment]
One actionable thing that we can do here is to update the examples to show `s3n://`.

**Comment by JoshRosen** [comment]
@jaley, I think that `s3://` worked for you in EMR because EMR aliases that to a `s3n://`-like FileSystem rather than the classic S3 block filesystem.  See https://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-file-systems.html and http://notes.mindprince.in/2014/08/01/difference-between-s3-block-and-s3-native-filesystem-on-hadoop.html

In a nutshell, I don't think that `spark-redshift` will work with the classic S3 block filesystem, but I don't see a super easy way to provide helpful programmatic warnings about this: we can't / shouldn't filter based on the URI since `s3://` _does_ work in some environments. I suppose we could check the class of the actual FileSystem that's returned for the URI. I'll spend a few minutes to see how hard this is to do. If it turns out to be really tricky, then I'll probably defer this task until someone else hits this issue.

**Comment by JoshRosen** [comment]
In #76, I updated `spark-redshift` to detect when the unsupported block FileSystem is being used and to throw a helpful error message. Note that we still do allow the `s3://` URI _scheme_; the exception is only triggered if that scheme's FileSystem implementation is the unsupported one.

Therefore, I'm going to resolve this issue as fixed.
