### ISSUE TITLE
Avro schema only file causes Redshift stl_load_errors: "Invalid AVRO file found. Unexpected end of AVRO file."

### ISSUE THREAD

**Issue by cfeduke** [databricks/spark-redshift#96]
When a part file contains no data and just the Avro schema, Redshift throws an exception:

```
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) 
Invalid operation: Load into table 'stg_device_attribute' failed.  Check 
'stl_load_errors' system table for details.;
```

Where the load error reads:

```
Invalid AVRO file found. Unexpected end of AVRO file.
```

My AVRO file just contains the schema for a number of shards where no records matched a `WHERE`-clause condition:

```
Obj...avro.codecsnappy.avro.schema..{"type":"record","name":"topLevelRecord","fields":[{"name":"roster_id","type":["long","null"]},{"name":"device_id","type":["long","null"]},{"name":"push_token","type":["string","null"]},{"name":"shard_id","type":["long","null"]},{"name":"device_type","type":["string","null"]},{"name":"device_date_created","type":["string","null"]}]} 
```

In my particular case I am running a query across 12 PostgreSQL databases which may not contain results. I can get around this problem by merging into a smaller number of partitions and hope there's at least one record in each part file by sacrificing Redshift parallelism on the load.

I am not sure what the solution is but it might be worth it to warn if a part file will have 0 records.

**Comment by JoshRosen** [comment]
@TELSER1 also ran into this in #89.

I wonder whether this is a Redshift bug or a `spark-avro` bug. As long as it's legal to create an Avro file containing no records, then I'd argue that Redshift should gracefully handle those files. According to the [Object Container File](https://avro.apache.org/docs/1.7.7/spec.html#Object+Container+Files) section of the Avro 1.7.7 spec, "A file consists of a _file header_, followed by one or more _file data blocks_". I wonder whether a valid empty Avro file needs to contain a file data block which explicitly says that it contains no objects. We should figure out whether the zero-record files that `spark-avro` is generated are legal.

This probably merits some testing with manually-generated Avro files in order to figure out which ones Redshift considers legal (vs. Spark). If Redshift can't support Avro files which contain no records, then we might have to add an option to `spark-avro` to try to avoid the creation of those files.

**Comment by cfeduke** [comment]
As a workaround for this issue I repartition the RDD, which I should have been doing from the beginning. I will look at the Avro spec and see if there is any mention of an empty block. (And I will check the Redshift docs too, sometimes they have notes for these sorts of edge cases.)

**Comment by cfeduke** [comment]
Re: Avro, looks like there [must be at least one](https://avro.apache.org/docs/1.7.6/spec.html#Object+Container+Files) file data block:

> A file consists of:
> - A file header, followed by
> - one or more file data blocks.

And then:

> A file data block consists of:
> - A long indicating the count of objects in this block.
> - A long indicating the size in bytes of the serialized objects in the current block, after any codec is applied
> - The serialized objects. If a codec is specified, this is compressed by that codec.
> - The file's 16-byte sync marker.
> Thus, each block's binary data can be efficiently extracted or skipped without deserializing the contents. The combination of block size, object counts, and sync markers enable detection of corrupt blocks and help ensure data integrity.

**Comment by cfeduke** [comment]
(Since you already included the Avro spec info in your reply no reason for me to duplicate it here.)

`avro-tools` (v1.7.7) processes my schema-only file with no problems but my guess is that there needs to be a file data block indicating 0 records for Redshift to process the file at all.

**Comment by JoshRosen** [comment]
This might be another piece of evidence in favor of exploring alternative data formats for transferring data to Redshift (see #73).

If we have an easy way to identify the empty files / partitions after the write is performed, then it might be possible to [use a manifest](https://docs.aws.amazon.com/redshift/latest/dg/loading-data-files-using-manifest.html) to explicitly specify only the non-empty partitions' files. We could probably use accumulators in order to record the number of records processed in each partition during the write in order to do this.

**Comment by cfeduke** [comment]
:+1: for manifest _though_ without explicitly rebalancing for Redshift's # of slices parallelism on `COPY` is compromised, but at this point when you have sparse/empty part files its probably not that big of a problem (failed `COPY`s are worse than less parallel ones!).

**Comment by cfeduke** [comment]
And of course don't forgot the other state, where all part files are empty. Probably shouldn't proceed to the `COPY` phase at all.

**Comment by JoshRosen** [comment]
Another benefit to using a manifest is the fact that it can mitigate S3 eventual consistency issues: https://docs.aws.amazon.com/redshift/latest/dg/managing-data-consistency.html

**Comment by barudwale20** [comment]
@JoshRosen It's been almost 5 years and I am still facing the same issue. Is there any solution to this apart from the manifest file?
I want to automate some of my tasks and making manifest each time does not make sense.
I couldn't find the solution hence asking here.
Will be really helpful if you could help.
